default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: hack-the-world
  password: hack-the-world

development:
  <<: *default
  database: hack-the-world_development
test:
  <<: *default
  database: hack-the-world_test
production:
  <<: *default
  database: hack-the-world_production
  username: hack-the-world
  password: <%= ENV['HACK-THE-WORLD_DATABASE_PASSWORD'] %>
